=== Project-AIMFREE/description_model/workshop/submodel_schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"properties": {
		"name": {
			"$ref": "#/definitions/name"
		},
		"revision": {
			"type": "string",
			"pattern": "^\\d*\\.\\d*\\.\\d*$"
		},
		"description": {
			"type": "string"
		},
		"properties": {
			"$ref": "#/definitions/typeObject"
		},
		"events": {
			"type": "object",
			"additionalProperties": {
				"$ref": "#/definitions/eventDescription"
			}
		},
		"operations": {
			"type": "object",
			"propertyNames": {
				"pattern": "^[A-Za-z_][A-Za-z0-9_.]*$"
			},
			"additionalProperties": {
				"$ref": "#/definitions/operationDescription"
			}
		}
	},
	"required": [
		"name",
		"revision"
	],
	"definitions": {
		"name": {
			"type": "string",
			"pattern": "^[A-Za-z_][A-Za-z0-9_]*$",
			"minLength": 3
		},
		"simpleTypes": {
			"enum": [
				"array",
				"boolean",
				"integer",
				"null",
				"number",
				"object",
				"string"
			]
		},
		"eventDescription": {
			"type": "object",
			"properties": {
				"description": {
					"type": "string"
				},
				"parameters": {
					"$ref": "#/definitions/typeObject"
				}
			}
		},
		"operationDescription": {
			"allOf": [
				{
					"$ref": "#/definitions/eventDescription"
				},
				{
					"properties": {
						"response": {
							"$ref": "#/definitions/typeDescription"
						}
					}
				}
			]
		},
		"typeDescription": {
			"type": "object",
			"properties": {
				"description": {
					"type": "string"
				},
				"type": {
					"$ref": "#/definitions/simpleTypes"
				}
			},
			"required": [
				"type"
			]
		},
		"typeObject": {
			"type": "object",
			"propertyNames": {
				"pattern": "^[A-Za-z_][A-Za-z0-9_.]*$"
			},
			"additionalProperties": {
				"$ref": "#/definitions/typeDescription"
			}
		}
	}
}

=== Project-AIMFREE/description_model/aimfree_models-ghn/location.json
{
		"name": "location",
		"revision": "0.0.1",
		"description": "a position estimation in 3d space with information about its confidence",
		"properties": {
			"pose": {
				"type": "object",
				"required": [
					"location",
					"confidence"
				],
				"properties": {
					"location": {
						"description": "the position estimation as object with properties x, y, z",
						"type": "object",
						"required": [
							"x",
							"y",
							"z"
						],
						"properties": {
							"x": {
								"type": "number"
							},
							"y": {
								"type": "number"
							},
							"z": {
								"type": "number"
							}
						}
					},
					"confidence": {
						"description": "an information about the confidence of the current position estimation. value between 0 and 1 (limits inclusive)",
						"type": "number",
						"minimum": 0.0,
						"maximum": 1.0
					}
				}
			}
		}
}
